package main

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestHome(t *testing.T) {
	// Initialize a new httptest.ResponseRecorder.
	rr := httptest.NewRecorder()

	// Initialize a new dummy http.Request.
	req, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// call the home handler fucntion
	home(rr, req)

	// Call the Result() method on the http.ResponseRecorder to get the
	// http.Response generated by the home handler.
	res := rr.Result()
	defer res.Body.Close()
	// Check that the status code written by the handler was 200.
	if rr.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d", rr.Code)
	}
	// Server header should be "Go"
	if rr.Header().Get("Server") != "Go" {
		t.Fatalf("expected Server header 'Go', got %q", rr.Header().Get("Server"))
	}
}
