// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: snippetbox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Expires       int32                  `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snippet) Reset() {
	*x = Snippet{}
	mi := &file_snippetbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snippet) ProtoMessage() {}

func (x *Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snippet.ProtoReflect.Descriptor instead.
func (*Snippet) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{0}
}

func (x *Snippet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Snippet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Snippet) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type GetSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetRequest) Reset() {
	*x = GetSnippetRequest{}
	mi := &file_snippetbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetRequest) ProtoMessage() {}

func (x *GetSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetRequest.ProtoReflect.Descriptor instead.
func (*GetSnippetRequest) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{1}
}

func (x *GetSnippetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippet       *Snippet               `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnippetResponse) Reset() {
	*x = GetSnippetResponse{}
	mi := &file_snippetbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnippetResponse) ProtoMessage() {}

func (x *GetSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnippetResponse.ProtoReflect.Descriptor instead.
func (*GetSnippetResponse) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{2}
}

func (x *GetSnippetResponse) GetSnippet() *Snippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

type CreateSnippetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Expires       int32                  `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetRequest) Reset() {
	*x = CreateSnippetRequest{}
	mi := &file_snippetbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetRequest) ProtoMessage() {}

func (x *CreateSnippetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetRequest.ProtoReflect.Descriptor instead.
func (*CreateSnippetRequest) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSnippetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSnippetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateSnippetRequest) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type CreateSnippetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippet       *Snippet               `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnippetResponse) Reset() {
	*x = CreateSnippetResponse{}
	mi := &file_snippetbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnippetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnippetResponse) ProtoMessage() {}

func (x *CreateSnippetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnippetResponse.ProtoReflect.Descriptor instead.
func (*CreateSnippetResponse) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSnippetResponse) GetSnippet() *Snippet {
	if x != nil {
		return x.Snippet
	}
	return nil
}

type HomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeRequest) Reset() {
	*x = HomeRequest{}
	mi := &file_snippetbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeRequest) ProtoMessage() {}

func (x *HomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeRequest.ProtoReflect.Descriptor instead.
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{5}
}

type HomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeResponse) Reset() {
	*x = HomeResponse{}
	mi := &file_snippetbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeResponse) ProtoMessage() {}

func (x *HomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snippetbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeResponse.ProtoReflect.Descriptor instead.
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return file_snippetbox_proto_rawDescGZIP(), []int{6}
}

func (x *HomeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_snippetbox_proto protoreflect.FileDescriptor

const file_snippetbox_proto_rawDesc = "" +
	"\n" +
	"\x10snippetbox.proto\x12\n" +
	"snippetbox\"c\n" +
	"\aSnippet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\x05R\aexpires\"#\n" +
	"\x11GetSnippetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"C\n" +
	"\x12GetSnippetResponse\x12-\n" +
	"\asnippet\x18\x01 \x01(\v2\x13.snippetbox.SnippetR\asnippet\"`\n" +
	"\x14CreateSnippetRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\x05R\aexpires\"F\n" +
	"\x15CreateSnippetResponse\x12-\n" +
	"\asnippet\x18\x01 \x01(\v2\x13.snippetbox.SnippetR\asnippet\"\r\n" +
	"\vHomeRequest\"(\n" +
	"\fHomeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xea\x01\n" +
	"\n" +
	"SnippetBox\x129\n" +
	"\x04Home\x12\x17.snippetbox.HomeRequest\x1a\x18.snippetbox.HomeResponse\x12K\n" +
	"\n" +
	"GetSnippet\x12\x1d.snippetbox.GetSnippetRequest\x1a\x1e.snippetbox.GetSnippetResponse\x12T\n" +
	"\rCreateSnippet\x12 .snippetbox.CreateSnippetRequest\x1a!.snippetbox.CreateSnippetResponseB&Z$snippetbox.paulkarayan.com/cmd/protob\x06proto3"

var (
	file_snippetbox_proto_rawDescOnce sync.Once
	file_snippetbox_proto_rawDescData []byte
)

func file_snippetbox_proto_rawDescGZIP() []byte {
	file_snippetbox_proto_rawDescOnce.Do(func() {
		file_snippetbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snippetbox_proto_rawDesc), len(file_snippetbox_proto_rawDesc)))
	})
	return file_snippetbox_proto_rawDescData
}

var file_snippetbox_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_snippetbox_proto_goTypes = []any{
	(*Snippet)(nil),               // 0: snippetbox.Snippet
	(*GetSnippetRequest)(nil),     // 1: snippetbox.GetSnippetRequest
	(*GetSnippetResponse)(nil),    // 2: snippetbox.GetSnippetResponse
	(*CreateSnippetRequest)(nil),  // 3: snippetbox.CreateSnippetRequest
	(*CreateSnippetResponse)(nil), // 4: snippetbox.CreateSnippetResponse
	(*HomeRequest)(nil),           // 5: snippetbox.HomeRequest
	(*HomeResponse)(nil),          // 6: snippetbox.HomeResponse
}
var file_snippetbox_proto_depIdxs = []int32{
	0, // 0: snippetbox.GetSnippetResponse.snippet:type_name -> snippetbox.Snippet
	0, // 1: snippetbox.CreateSnippetResponse.snippet:type_name -> snippetbox.Snippet
	5, // 2: snippetbox.SnippetBox.Home:input_type -> snippetbox.HomeRequest
	1, // 3: snippetbox.SnippetBox.GetSnippet:input_type -> snippetbox.GetSnippetRequest
	3, // 4: snippetbox.SnippetBox.CreateSnippet:input_type -> snippetbox.CreateSnippetRequest
	6, // 5: snippetbox.SnippetBox.Home:output_type -> snippetbox.HomeResponse
	2, // 6: snippetbox.SnippetBox.GetSnippet:output_type -> snippetbox.GetSnippetResponse
	4, // 7: snippetbox.SnippetBox.CreateSnippet:output_type -> snippetbox.CreateSnippetResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_snippetbox_proto_init() }
func file_snippetbox_proto_init() {
	if File_snippetbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snippetbox_proto_rawDesc), len(file_snippetbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snippetbox_proto_goTypes,
		DependencyIndexes: file_snippetbox_proto_depIdxs,
		MessageInfos:      file_snippetbox_proto_msgTypes,
	}.Build()
	File_snippetbox_proto = out.File
	file_snippetbox_proto_goTypes = nil
	file_snippetbox_proto_depIdxs = nil
}
