// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: snippetbox.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnippetBox_Home_FullMethodName          = "/snippetbox.SnippetBox/Home"
	SnippetBox_GetSnippet_FullMethodName    = "/snippetbox.SnippetBox/GetSnippet"
	SnippetBox_CreateSnippet_FullMethodName = "/snippetbox.SnippetBox/CreateSnippet"
)

// SnippetBoxClient is the client API for SnippetBox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnippetBoxClient interface {
	Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error)
	GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*GetSnippetResponse, error)
	CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*CreateSnippetResponse, error)
}

type snippetBoxClient struct {
	cc grpc.ClientConnInterface
}

func NewSnippetBoxClient(cc grpc.ClientConnInterface) SnippetBoxClient {
	return &snippetBoxClient{cc}
}

func (c *snippetBoxClient) Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, SnippetBox_Home_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetBoxClient) GetSnippet(ctx context.Context, in *GetSnippetRequest, opts ...grpc.CallOption) (*GetSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnippetResponse)
	err := c.cc.Invoke(ctx, SnippetBox_GetSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snippetBoxClient) CreateSnippet(ctx context.Context, in *CreateSnippetRequest, opts ...grpc.CallOption) (*CreateSnippetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnippetResponse)
	err := c.cc.Invoke(ctx, SnippetBox_CreateSnippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnippetBoxServer is the server API for SnippetBox service.
// All implementations must embed UnimplementedSnippetBoxServer
// for forward compatibility.
type SnippetBoxServer interface {
	Home(context.Context, *HomeRequest) (*HomeResponse, error)
	GetSnippet(context.Context, *GetSnippetRequest) (*GetSnippetResponse, error)
	CreateSnippet(context.Context, *CreateSnippetRequest) (*CreateSnippetResponse, error)
	mustEmbedUnimplementedSnippetBoxServer()
}

// UnimplementedSnippetBoxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnippetBoxServer struct{}

func (UnimplementedSnippetBoxServer) Home(context.Context, *HomeRequest) (*HomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Home not implemented")
}
func (UnimplementedSnippetBoxServer) GetSnippet(context.Context, *GetSnippetRequest) (*GetSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnippet not implemented")
}
func (UnimplementedSnippetBoxServer) CreateSnippet(context.Context, *CreateSnippetRequest) (*CreateSnippetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnippet not implemented")
}
func (UnimplementedSnippetBoxServer) mustEmbedUnimplementedSnippetBoxServer() {}
func (UnimplementedSnippetBoxServer) testEmbeddedByValue()                    {}

// UnsafeSnippetBoxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnippetBoxServer will
// result in compilation errors.
type UnsafeSnippetBoxServer interface {
	mustEmbedUnimplementedSnippetBoxServer()
}

func RegisterSnippetBoxServer(s grpc.ServiceRegistrar, srv SnippetBoxServer) {
	// If the following call panics, it indicates UnimplementedSnippetBoxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnippetBox_ServiceDesc, srv)
}

func _SnippetBox_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetBoxServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetBox_Home_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetBoxServer).Home(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetBox_GetSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetBoxServer).GetSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetBox_GetSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetBoxServer).GetSnippet(ctx, req.(*GetSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnippetBox_CreateSnippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnippetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetBoxServer).CreateSnippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnippetBox_CreateSnippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetBoxServer).CreateSnippet(ctx, req.(*CreateSnippetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnippetBox_ServiceDesc is the grpc.ServiceDesc for SnippetBox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnippetBox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snippetbox.SnippetBox",
	HandlerType: (*SnippetBoxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Home",
			Handler:    _SnippetBox_Home_Handler,
		},
		{
			MethodName: "GetSnippet",
			Handler:    _SnippetBox_GetSnippet_Handler,
		},
		{
			MethodName: "CreateSnippet",
			Handler:    _SnippetBox_CreateSnippet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snippetbox.proto",
}
