version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gocritic
    - bodyclose
    - noctx
    - gosec
    - contextcheck
  settings:
    govet:
      enable:
        - copylocks
        - shadow
    errcheck:
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprintf
        - fmt.Fprint
        - (net/http.ResponseWriter).Write
        - (*net/http.response).Write
    gocritic:
      enabled-checks:
        - sloppyReassign
        - unnamedResult
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - noctx
          - errcheck
          - gosec
          - contextcheck
          - bodyclose
